### PR TITLE
Add Kamino pool/vault APR/APY to metrics endpoint

### PR DESCRIPTION
**Pull request by peroxy**
Request:
```shell
curl --location --request GET 'localhost:8888/strategies/HcHkvZEDechu7bruV8zvMN11v9yHg3iY4QHNgrYUATmg/metrics?env=mainnet-beta'
```

Response:

```json
    {
        "totalValueLocked": "1012302.853113711462552349499999999999999",
        "sharePrice": "567.8370414515869161019030909775414610626",
        "sharesIssued": "1782.734797515",
        "profitAndLoss": "0",
        "apy": {
            "vault": {
                "totalApr": "0.0065268898208785816",
                "totalApy": "0.006548177645201093639345412121010669901",
                "feeApr": "0.0025974215907447144",
                "feeApy": "0.002600788546820525174284461486065192352",
                "rewardsApr": [
                    "0.000470253850371326",
                    "0.0034592143797625412",
                    "0"
                ],
                "rewardsApy": [
                    "0.000470364133975213747426088866245985434",
                    "0.003465187918013390249771670780549821515",
                    "0"
                ]
            },
            "kamino": [
                {
                    "apy": "0.093516940245063105426378891700337744247",
                    "apr": "0.08941000187997401398158445821819973033692",
                    "totalInvestment": "1012302.853113711462552349499999999999999",
                    "totalReturn": "90510",
                    "token": "LDO",
                    "rewardIsOption": false,
                    "rewardsPerMonth": "3500",
                    "rewardsPerHour": "4.704301075268817204301075268817204301075",
                    "validFrom": "2023-01-01T00:00:00.000Z",
                    "validTo": "2023-01-31T23:59:59.999Z"
                }
            ],
            "totalApy": "0.100065117890264199065724303821348414148"
        },
        "strategy": "ByXB4xCxVhmUEmQj3Ut7byZ1Hbva1zhKjaVcv3jBMN7E"
    },
```

### CODE REVIEW

**Comment by silviutroscot** [comment]
the APY is the APR compounded daily or how often do we consider compounding in APY calc?

**Comment by peroxy** [comment]
> the APY is the APR compounded daily or how often do we consider compounding in APY calc?

Same way we do the calculations on the frontend - the returns are estimated based on the last 24h trade fees earned, annualized

**Comment by y2kappa** [comment]
hey, while you're here, can you please add also vaultBalances { token_a_invested, token_a_available, token_b_invested, token_b_available, token_a_total, token_a_total_usd, token_b_total, token_b_total_usd}

**Comment by peroxy** [comment]
> vaultBalances { token_a_invested, token_a_available, token_b_invested, token_b_available, token_a_total, token_a_total_usd, token_b_total, token_b_total_usd}

Will add

**Comment by peroxy** [comment]
@y2kappa added vault balances

**Review by y2kappa — APPROVED** [review]

**Pull request merged**
